sudo: enabled
dist: xenial
language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
os:
  - linux

install:
  - python setup.py install

script: pytest --disable-warnings -p no:warnings -W test/test_aspired.py
